version: '3'
services:
  zoo1:
    image: wurstmeister/zookeeper
    container_name: zoo1
    restart: always
    ports:
      - '2181:2181'
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 server.4=zoo4:2888:3888 server.5=zoo5:2888:3888

  zoo2:
    image: wurstmeister/zookeeper
    container_name: zoo2
    restart: always
    ports:
      - '2182:2181'
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 server.4=zoo4:2888:3888 server.5=zoo5:2888:3888

  zoo3:
    image: wurstmeister/zookeeper
    container_name: zoo3
    restart: always
    ports:
      - '2183:2181'
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 server.4=zoo4:2888:3888 server.5=zoo5:2888:3888

  zoo4:
    image: wurstmeister/zookeeper
    container_name: zoo4
    restart: always
    ports:
      - '2184:2181'
    environment:
      ZOO_MY_ID: 4
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 server.4=zoo4:2888:3888 server.5=zoo5:2888:3888

  zoo5:
    image: wurstmeister/zookeeper
    container_name: zoo5
    restart: always
    ports:
      - '2185:2181'
    environment:
      ZOO_MY_ID: 5
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 server.4=zoo4:2888:3888 server.5=zoo5:2888:3888

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183,zoo4:2184,zoo5:2185
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - zoo4
      - zoo5
